//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TopGear_WebApi_DependencyInjection2.Models
{
    using Microsoft.AspNet.Identity.EntityFramework;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class WebApiDependencyInjectionDBEntities1 : DbContext
    {
        public WebApiDependencyInjectionDBEntities1()
            : base("name=WebApiDependencyInjectionDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Post> Posts { get; set; }
        public virtual DbSet<User> Users { get; set; }

        public System.Data.Entity.DbSet<TopGear_WebApi_DependencyInjection2.Models.PostDTO> PostDTOes { get; set; }
    }
}
